name: Generate and publish documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build documentation with Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          build-command: "sphinx-build -b html . html"
          docs-folder: 'docs/'
