name: linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        cxx: [g++-11, g++-12, g++-13, clang++]
        include:
          - cxx: g++-11
            install: |
              brew install gcc@11 ninja binutils
              brew link --force binutils
          - cxx: g++-12
            install: |
              brew install gcc@12 ninja binutils
              brew link --force binutils
          - cxx: g++-13
            install: |
              brew install gcc@13 ninja binutils
              brew link --force binutils
          - cxx: clang++
            install: |
              brew install llvm@17 ninja binutils
              brew link --force binutils

    steps:
    - uses: actions/checkout@master

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
              -DFLUX_BUILD_BENCHMARKS=${{matrix.build_type == 'Release'}} \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
