# Based on macos.yml from {fmt}
# https://github.com/fmtlib/fmt/blob/master/.github/workflows/macos.yml

name: macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        cxx: [g++-12, g++-13, /usr/local/opt/llvm/bin/clang++]
        include:
          - cxx: g++-12
            install: brew install gcc@12 ninja
          - cxx: g++-13
            install: |
              brew update
              brew install gcc@13 ninja
          - cxx: /usr/local/opt/llvm/bin/clang++
            install: |
              brew update
              brew install llvm@16 ninja

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
               -DFLUX_BUILD_BENCHMARKS=${{matrix.build_type == 'Release'}} \
               $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
